language: python
python:
  - "2.7"
install:
  - pip install nltk --use-mirrors
  - python -c 'import nltk; nltk.download("punkt")'
  - python -c 'import nltk; nltk.download("maxent_treebank_pos_tagger")'
script: nosetests
